### PR TITLE
Move source files to src dir, add os import

### PR DESCRIPTION
**Pull request by ChronosXYZ**
Now it compiles correctly

### CODE REVIEW

**Comment by ChronosX88** [comment]
Now it compiles correctly

**Comment by Smartyue** [comment]
Hello sir! 
Sorry, I don't really like to put the code in the "src" directory, just like java.

**Comment by ChronosXYZ** [comment]
:(

but it makes the project structure more orderly, clear, and it does not mixing with other files.

**Comment by ChronosXYZ** [comment]
So, you decided to close this PR?

**Comment by Smartyue** [comment]
Yes, I am sorry about that.
Thank you for your suggestion.


发自我的iPhone

------------------ Original ------------------

**Pull request closed without merging**
